// Generated by CoffeeScript 1.6.2
var count, myApp, yourApp;

myApp = angular.module('MyApp', ['YourApp']);

myApp.controller('MyCtrl', [
  '$scope', 'inc', function($scope, inc) {
    $scope.fizzbuzz = function(n) {
      var f;

      f = function(m, s) {
        if (n % m) {
          return "";
        } else {
          return s;
        }
      };
      return f(3, "fizz") + f(5, "buzz") || n;
    };
    $scope.calender = [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]];
    return $scope.inc = inc;
  }
]);

yourApp = angular.module('YourApp', []);

yourApp.controller('YourCtrl', [
  '$scope', 'inc', function($scope, inc) {
    $scope.names = ["富士通", "IBM", "NTTD"];
    return $scope.inc = inc;
  }
]);

count = 0;

yourApp.factory('inc', function() {
  var Hoge;

  Hoge = (function() {
    function Hoge() {}

    Hoge.prototype.set = function(n) {
      return count = n;
    };

    Hoge.prototype.get = function() {
      return count;
    };

    return Hoge;

  })();
  return new Hoge();
});
