// Generated by CoffeeScript 1.6.2
describe('YourCtrl', function() {
  var names, scope;

  scope = null;
  names = null;
  beforeEach(function() {
    module('YourApp');
    inject(function($rootScope, $controller) {
      var ctrl;

      scope = $rootScope.$new();
      return ctrl = $controller('YourCtrl', {
        $scope: scope
      });
    });
    return names = scope.names;
  });
  describe('#inc', function() {
    return it('should be inc num.', function() {
      scope.inc.set(100);
      return expect(scope.inc.get()).toBe(100);
    });
  });
  return describe('#names', function() {
    return it('should be 長さ3の配列', function() {
      return expect(names.length).toBe(3);
    });
  });
});

describe('MyCtrl', function() {
  var calender, fizzbuzz, scope;

  scope = null;
  fizzbuzz = null;
  calender = null;
  beforeEach(function() {
    module('MyApp');
    inject(function($rootScope, $controller) {
      var ctrl;

      scope = $rootScope.$new();
      return ctrl = $controller('MyCtrl', {
        $scope: scope
      });
    });
    fizzbuzz = scope.fizzbuzz;
    return calender = scope.calender;
  });
  describe('#inc', function() {
    return it('should be 3?', function() {
      return expect(scope.inc.get()).toBe(100);
    });
  });
  describe('#calender', function() {
    return it('should be array of 6 x 7', function() {
      expect(calender.length).toBe(6);
      return expect(calender[0].length).toBe(7);
    });
  });
  return describe('#fizzbuzz', function() {
    it('３の倍数で"fizz"を返す', function() {
      expect(fizzbuzz(-6)).toBe("fizz");
      expect(fizzbuzz(-3)).toBe("fizz");
      expect(fizzbuzz(3)).toBe("fizz");
      expect(fizzbuzz(6)).toBe("fizz");
      expect(fizzbuzz(9)).toBe("fizz");
      return expect(fizzbuzz(12)).toBe("fizz");
    });
    it('５の倍数で"buzz"を返す', function() {
      expect(fizzbuzz(-10)).toBe("buzz");
      expect(fizzbuzz(-5)).toBe("buzz");
      expect(fizzbuzz(5)).toBe("buzz");
      return expect(fizzbuzz(10)).toBe("buzz");
    });
    it('３と５の公倍数であれば"fizzbuzz"を返す', function() {
      expect(fizzbuzz(-15)).toBe("fizzbuzz");
      expect(fizzbuzz(0)).toBe("fizzbuzz");
      expect(fizzbuzz(15)).toBe("fizzbuzz");
      expect(fizzbuzz(30)).toBe("fizzbuzz");
      return expect(fizzbuzz(45)).toBe("fizzbuzz");
    });
    return it('３の倍数でも５の倍数でもなければ数字をnumber型で返す', function() {
      expect(fizzbuzz(1)).toBe(1);
      expect(fizzbuzz(2)).toBe(2);
      expect(fizzbuzz(4)).toBe(4);
      expect(fizzbuzz(7)).toBe(7);
      expect(fizzbuzz(101)).toBe(101);
      return expect(fizzbuzz(-101)).toBe(-101);
    });
  });
});
